### PR TITLE
Fix #281

### LINKED ISSUE #281: Format Short Broken
After merge #278 I noticed `mix dialyzer --format short` fails with an error in this repository itself:

```
** (CaseClauseError) no case clause matching: []
    lib/dialyxir/dialyzer.ex:47: Dialyxir.Dialyzer.Runner.run/2
    lib/dialyxir/dialyzer.ex:71: Dialyxir.Dialyzer.dialyze/3
    lib/mix/tasks/dialyzer.ex:258: Mix.Tasks.Dialyzer.run_dialyzer/2
    lib/mix/tasks/dialyzer.ex:190: Mix.Tasks.Dialyzer.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

@evnu do you mind taking a look? I'm guessing the `:short` clause needs similar updates to the `:dialyxir` format clause.

### PR DESCRIPTION
**Pull request by evnu**
This merge request fixes #281. Warning formatters other than `dialyxir` were broken by #278.

### CODE REVIEW

File: lib/dialyxir/formatter.ex [hunk 1]
```diff
@@ -67,18 +60,45 @@ defmodule Dialyxir.Formatter do
...
   def format_and_filter(warnings, filterer, filter_map_args, :short) do
     filter_map = filterer.filter_map(filter_map_args)
 
     {formatted_warnings, _skip_map} = filter_warnings(warnings, filterer, filter_map)
 
-    formatted_warnings
-    |> filter_legacy_warnings(filterer)
-    |> Enum.map(&format_warning(&1, :short))
+    formatted_warnings =
+      formatted_warnings
```
Comment (asummers) [inline lib/dialyxir/formatter.ex]: This guy should probably be called `filtered_warnings` on line 71. But feel free to punt that since it was an existing issue.
